
export const apiUserHost = "https://mf-api-user-sj8ek.ondigitalocean.app/mf-2/api/users/"
export const apiCustomerHost = "https://mf-api-customer-nccrp.ondigitalocean.app/api/customers/"
export const apiChatHost = "https://mf-api-chat-6m4o7.ondigitalocean.app/api/messages/"
export const apiOrgHost = "https://mf-api-aoc-e7o4q.ondigitalocean.app/api/organization/"
export const apiFlowBuilderHost = "https://mf-api-flowbuilder-3ilv9.ondigitalocean.app/api/bots/"
export const apiBotHost = "https://mf-api-bot-g5e9j.ondigitalocean.app/api/botmessages/"
export const apiBroadcastHost = "https://mf-api-broadcast-pgcnt.ondigitalocean.app/api/broadcasts/"
export const apiAnalysisHost = "https://mf-api-analysis-4u9px.ondigitalocean.app/api/analysis"
export const apiLogHost = "https://mf-api-log-x8cl9.ondigitalocean.app/api/logs/"