/* action types: should be unique by actions */
export const API_POST_TYPE_ERROR = "API POST TYPE ERROR";

export const API_GET_FETCHING = "API GET FETCHING";
export const API_GET_RETRIEVED = "API GET RETRIEVED";
export const API_GET_RETRIEVED_WITH_NO_DATA = "API GET RETRIEVED WITH NO DATA";
export const API_GET_CONNECTION_ERROR = "API GET CONNECTION ERROR";
export const API_GET_ERROR = "API GET ERROR";
export const API_GET_RESET = "API GET RESET";

export const API_UPDATE_REQUESTING = "API UPDATE REQUESTING";
export const API_UPDATE_FETCHING = "API UPDATE FETCHING";
export const API_UPDATE_SUCCESS = "API UPDATE SUCCESS";
export const API_UPDATE_CONNECTION_ERROR = "API UPDATE CONNECTION ERROR";
export const API_UPDATE_ERROR = "API UPDATE ERROR";

export const API_PUT_REQUESTING = "API PUT REQUESTING";
export const API_PUT_FETCHING = "API PUT FETCHING";
export const API_PUT_SUCCESS = "API PUT SUCCESS";
export const API_PUT_CONNECTION_ERROR = "API PUT CONNECTION ERROR";
export const API_PUT_ERROR = "API PUT ERROR";

export const API_POST_REQUESTING = "API POST REQUESTING";
export const API_POST_FETCHING = "API POST FETCHING";
export const API_POST_SUCCESS = "API POST SUCCESS";
export const API_POST_CONNECTION_ERROR = "API POST CONNECTION ERROR";
export const API_POST_ERROR = "API POST ERROR";
export const API_POST_RESET = "API POST RESET";

export const API_DELETE_REQUESTING = "API DELETE REQUESTING";
export const API_DELETE_FETCHING = "API DELETE FETCHING";
export const API_DELETE_SUCCESS = "API DELETE SUCCESS";
export const API_DELETE_CONNECTION_ERROR = "API DELETE CONNECTION ERROR";
export const API_DELETE_ERROR = "API DELETE ERROR";